# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
# Import your libraries:

%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
#!pip install sqlalchemy
#from sqlalchemy import create_engine

In [2]:
#pip install Flask-SQLAlchemyimport pymysql


# Challenge 0 - Load,Query and Create connection of your Dataset

#### A lot of the times you won't have files already saved in an Excel or CSV file for you to prepare your data, implying that a lot of times you'll be extracting data from a Data Warehouse or Data Lake, majority of times through SQL.
#### A couple of times you may want to do some queries on your table in mySQL to get a slight view on what you have in hands,
#### so let's simulate that!

#### First we'll need to create a database and table in mySQL:

##### 1ยบ- Open the austin_weather.sql file in MySQL Workbench and run the script into a desired schema.

#### 2ยบ- As we are in mySQL Workbench, we can do some queries there, to get an overview on some characteristics of our data:
 - a) How many days are recorded in the dataset?
 - b) What is the day with the Highest Temperature in Fahrenheit (column TempHighF)
 - c) What is the average Humidity across all days? (column HumidityAvgPercent)
 - d) Top 10 days, where SeaLevelPressureAvgInches is the highest, knowing DewPointAvgF is higher than 28 ?

In [ ]:
# Write your answers below:

# a) 1319
# b) 2017-07-29 00:00:00 is 107
# c) 66.570887
# d)

#### Now that you explored a couple of elements in your table, let's bring your table into this jupyter notebook, by creating a Python-SQL connection like you did on MySQL Project!
#### In case you need a little refresher check this [link](https://www.dataquest.io/blog/sql-insert-tutorial/).
##### 1ยบ - Create a connection using sqlalchemy from python to mysql 
##### 2ยบ- Load the table into a variable called weather_df

In [158]:
import mysql.connector

In [159]:
import getpass
saved_password = getpass.getpass()

In [160]:
cnx = mysql.connector.connect(user='root', password = saved_password, database='lab_14', port=3306)

In [161]:
cnx.is_connected()

True

In [162]:
cursor = cnx.cursor(buffered=True)

In [163]:
query = ("SELECT * FROM austin_weather;")
cursor.execute(query)
results = cursor.fetchall()
results

[(datetime.datetime(2013, 12, 21, 0, 0),
  74,
  60,
  45,
  '67',
  '49',
  '43',
  '93',
  '75',
  '57',
  '29.86',
  '29.68',
  '29.59',
  '10',
  '7',
  '2',
  '20',
  '4',
  '31',
  '0.46',
  'Rain , Thunderstorm'),
 (datetime.datetime(2013, 12, 22, 0, 0),
  56,
  48,
  39,
  '43',
  '36',
  '28',
  '93',
  '68',
  '43',
  '30.41',
  '30.13',
  '29.87',
  '10',
  '10',
  '5',
  '16',
  '6',
  '25',
  '0',
  ' '),
 (datetime.datetime(2013, 12, 23, 0, 0),
  58,
  45,
  32,
  '31',
  '27',
  '23',
  '76',
  '52',
  '27',
  '30.56',
  '30.49',
  '30.41',
  '10',
  '10',
  '10',
  '8',
  '3',
  '12',
  '0',
  ' '),
 (datetime.datetime(2013, 12, 24, 0, 0),
  61,
  46,
  31,
  '36',
  '28',
  '21',
  '89',
  '56',
  '22',
  '30.56',
  '30.45',
  '30.3',
  '10',
  '10',
  '7',
  '12',
  '4',
  '20',
  '0',
  ' '),
 (datetime.datetime(2013, 12, 25, 0, 0),
  58,
  50,
  41,
  '44',
  '40',
  '36',
  '86',
  '71',
  '56',
  '30.41',
  '30.33',
  '30.27',
  '10',
  '10',
  '7',
  '10',
  '2',
  '16',
  'T',
  ' '),
 (datetime.datetime(2013, 12, 26, 0, 0),
  57,
  48,
  39,
  '39',
  '36',
  '33',
  '79',
  '63',
  '47',
  '30.47',
  '30.4',
  '30.34',
  '10',
  '9',
  '7',
  '12',
  '3',
  '17',
  '0',
  ' '),
 (datetime.datetime(2013, 12, 27, 0, 0),
  60,
  53,
  45,
  '41',
  '39',
  '37',
  '83',
  '65',
  '47',
  '30.46',
  '30.39',
  '30.34',
  '10',
  '9',
  '7',
  '7',
  '1',
  '11',
  'T',
  ' '),
 (datetime.datetime(2013, 12, 28, 0, 0),
  62,
  51,
  40,
  '43',
  '39',
  '33',
  '92',
  '64',
  '36',
  '30.33',
  '30.17',
  '30.04',
  '10',
  '10',
  '7',
  '10',
  '2',
  '14',
  'T',
  ' '),
 (datetime.datetime(2013, 12, 29, 0, 0),
  64,
  50,
  36,
  '49',
  '41',
  '28',
  '92',
  '76',
  '60',
  '30.31',
  '30.1',
  '29.99',
  '10',
  '10',
  '4',
  '17',
  '5',
  '24',
  '0',
  ' '),
 (datetime.datetime(2013, 12, 30, 0, 0),
  44,
  40,
  35,
  '31',
  '26',
  '21',
  '75',
  '60',
  '45',
  '30.44',
  '30.33',
  '30.26',
  '10',
  '10',
  '10',
  '13',
  '5',
  '21',
  '0',
  ' '),
 (datetime.datetime(2013, 12, 31, 0, 0),
  55,
  46,
  36,
  '31',
  '28',
  '23',
  '76',
  '54',
  '32',
  '30.49',
  '30.39',
  '30.27',
  '10',
  '10',
  '10',
  '8',
  '1',
  '12',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 1, 0, 0),
  69,
  54,
  39,
  '51',
  '42',
  '30',
  '83',
  '68',
  '52',
  '30.25',
  '30.11',
  '30.01',
  '10',
  '10',
  '8',
  '13',
  '4',
  '22',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 2, 0, 0),
  55,
  44,
  33,
  '39',
  '26',
  '19',
  '83',
  '55',
  '26',
  '30.49',
  '30.37',
  '30.15',
  '10',
  '10',
  '9',
  '21',
  '8',
  '31',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 3, 0, 0),
  58,
  43,
  28,
  '37',
  '22',
  '18',
  '75',
  '49',
  '22',
  '30.48',
  '30.35',
  '30.14',
  '10',
  '10',
  '10',
  '14',
  '4',
  '21',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 4, 0, 0),
  71,
  57,
  42,
  '55',
  '48',
  '38',
  '89',
  '68',
  '47',
  '30.12',
  '29.95',
  '29.81',
  '10',
  '10',
  '8',
  '16',
  '7',
  '28',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 5, 0, 0),
  59,
  47,
  34,
  '54',
  '32',
  '15',
  '87',
  '59',
  '31',
  '30.48',
  '30.08',
  '29.79',
  '10',
  '10',
  '4',
  '21',
  '10',
  '34',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 6, 0, 0),
  36,
  29,
  22,
  '15',
  '8',
  '2',
  '50',
  '38',
  '26',
  '30.8',
  '30.68',
  '30.5',
  '10',
  '10',
  '10',
  '17',
  '7',
  '27',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 7, 0, 0),
  48,
  35,
  22,
  '29',
  '11',
  '4',
  '68',
  '43',
  '17',
  '30.66',
  '30.52',
  '30.36',
  '10',
  '10',
  '10',
  '13',
  '5',
  '22',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 8, 0, 0),
  53,
  47,
  40,
  '51',
  '45',
  '30',
  '93',
  '75',
  '57',
  '30.33',
  '30.2',
  '30.12',
  '10',
  '2',
  '1',
  '12',
  '1',
  '18',
  '0.16',
  'Rain'),
 (datetime.datetime(2014, 1, 9, 0, 0),
  70,
  62,
  53,
  '60',
  '55',
  '50',
  '93',
  '80',
  '66',
  '30.18',
  '30.11',
  '30',
  '10',
  '4',
  '0',
  '12',
  '3',
  '19',
  '0',
  'Fog'),
 (datetime.datetime(2014, 1, 10, 0, 0),
  72,
  65,
  57,
  '64',
  '61',
  '54',
  '93',
  '81',
  '68',
  '29.97',
  '29.87',
  '29.75',
  '10',
  '8',
  '1',
  '13',
  '6',
  '21',
  '0.1',
  'Rain'),
 (datetime.datetime(2014, 1, 11, 0, 0),
  75,
  62,
  48,
  '54',
  '37',
  '20',
  '93',
  '53',
  '13',
  '30.16',
  '30.06',
  '29.87',
  '10',
  '9',
  '5',
  '12',
  '3',
  '19',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 12, 0, 0),
  67,
  57,
  46,
  '58',
  '47',
  '33',
  '84',
  '68',
  '52',
  '30.12',
  '30.01',
  '29.9',
  '10',
  '10',
  '10',
  '15',
  '4',
  '24',
  '0.01',
  'Rain'),
 (datetime.datetime(2014, 1, 13, 0, 0),
  71,
  57,
  43,
  '60',
  '36',
  '17',
  '87',
  '51',
  '14',
  '30.16',
  '30.01',
  '29.86',
  '10',
  '9',
  '7',
  '17',
  '7',
  '29',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 14, 0, 0),
  76,
  57,
  37,
  '31',
  '25',
  '20',
  '70',
  '41',
  '12',
  '30.34',
  '30.13',
  '30.01',
  '10',
  '10',
  '10',
  '16',
  '5',
  '29',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 15, 0, 0),
  64,
  52,
  40,
  '29',
  '23',
  '16',
  '49',
  '35',
  '21',
  '30.47',
  '30.33',
  '30.17',
  '10',
  '10',
  '10',
  '14',
  '4',
  '21',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 16, 0, 0),
  72,
  56,
  40,
  '31',
  '27',
  '23',
  '55',
  '38',
  '20',
  '30.21',
  '30.13',
  '30.06',
  '10',
  '10',
  '10',
  '14',
  '4',
  '20',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 17, 0, 0),
  64,
  54,
  43,
  '31',
  '20',
  '15',
  '45',
  '31',
  '17',
  '30.37',
  '30.29',
  '30.21',
  '10',
  '10',
  '9',
  '14',
  '5',
  '21',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 18, 0, 0),
  70,
  54,
  37,
  '41',
  '33',
  '23',
  '59',
  '45',
  '31',
  '30.26',
  '30.19',
  '30.1',
  '10',
  '10',
  '10',
  '12',
  '2',
  '19',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 19, 0, 0),
  72,
  59,
  45,
  '41',
  '30',
  '18',
  '64',
  '39',
  '14',
  '30.35',
  '30.22',
  '30.12',
  '10',
  '10',
  '10',
  '9',
  '3',
  '16',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 20, 0, 0),
  82,
  64,
  46,
  '51',
  '36',
  '23',
  '71',
  '44',
  '17',
  '30.16',
  '30',
  '29.85',
  '10',
  '10',
  '10',
  '16',
  '5',
  '26',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 21, 0, 0),
  63,
  51,
  38,
  '28',
  '23',
  '19',
  '59',
  '39',
  '19',
  '30.43',
  '30.31',
  '30.19',
  '10',
  '10',
  '10',
  '15',
  '6',
  '25',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 22, 0, 0),
  70,
  54,
  37,
  '39',
  '27',
  '24',
  '70',
  '45',
  '19',
  '30.23',
  '30.11',
  '30.01',
  '10',
  '10',
  '10',
  '12',
  '4',
  '18',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 23, 0, 0),
  56,
  42,
  27,
  '42',
  '29',
  '20',
  '78',
  '64',
  '50',
  '30.73',
  '30.47',
  '30.06',
  '10',
  '8',
  '2',
  '20',
  '9',
  '31',
  '0.06',
  'Rain , Snow'),
 (datetime.datetime(2014, 1, 24, 0, 0),
  40,
  33,
  26,
  '22',
  '17',
  '10',
  '81',
  '60',
  '39',
  '30.76',
  '30.63',
  '30.4',
  '10',
  '9',
  '3',
  '16',
  '5',
  '24',
  '0.05',
  ' '),
 (datetime.datetime(2014, 1, 25, 0, 0),
  70,
  48,
  26,
  '38',
  '27',
  '22',
  '85',
  '53',
  '20',
  '30.38',
  '30.19',
  '30.02',
  '10',
  '10',
  '8',
  '8',
  '1',
  '14',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 26, 0, 0),
  76,
  60,
  43,
  '45',
  '39',
  '33',
  '76',
  '52',
  '27',
  '30',
  '29.84',
  '29.69',
  '10',
  '10',
  '10',
  '12',
  '3',
  '20',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 27, 0, 0),
  60,
  47,
  34,
  '43',
  '23',
  '5',
  '66',
  '44',
  '21',
  '30.28',
  '30.09',
  '29.81',
  '10',
  '10',
  '10',
  '21',
  '9',
  '32',
  '0.02',
  'Rain'),
 (datetime.datetime(2014, 1, 28, 0, 0),
  39,
  33,
  27,
  '19',
  '14',
  '7',
  '69',
  '48',
  '27',
  '30.51',
  '30.4',
  '30.27',
  '10',
  '10',
  '10',
  '15',
  '6',
  '23',
  '0.05',
  'Rain'),
 (datetime.datetime(2014, 1, 29, 0, 0),
  49,
  38,
  27,
  '19',
  '13',
  '9',
  '63',
  '42',
  '21',
  '30.52',
  '30.41',
  '30.29',
  '10',
  '10',
  '10',
  '15',
  '5',
  '23',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 30, 0, 0),
  65,
  48,
  31,
  '51',
  '36',
  '20',
  '80',
  '64',
  '48',
  '30.26',
  '30.06',
  '29.9',
  '10',
  '10',
  '10',
  '15',
  '7',
  '27',
  '0',
  ' '),
 (datetime.datetime(2014, 1, 31, 0, 0),
  80,
  68,
  55,
  '59',
  '54',
  '51',
  '86',
  '64',
  '42',
  '29.96',
  '29.87',
  '29.79',
  '10',
  '10',
  '9',
  '14',
  '9',
  '25',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 1, 0, 0),
  76,
  66,
  55,
  '62',
  '59',
  '41',
  '81',
  '71',
  '60',
  '29.91',
  '29.81',
  '29.75',
  '10',
  '10',
  '9',
  '14',
  '6',
  '26',
  'T',
  'Rain'),
 (datetime.datetime(2014, 2, 2, 0, 0),
  55,
  45,
  35,
  '40',
  '33',
  '27',
  '79',
  '69',
  '59',
  '30.27',
  '30.09',
  '29.9',
  '10',
  '8',
  '4',
  '18',
  '11',
  '29',
  '0.02',
  'Rain'),
 (datetime.datetime(2014, 2, 3, 0, 0),
  46,
  40,
  34,
  '38',
  '33',
  '28',
  '82',
  '74',
  '65',
  '30.28',
  '30.17',
  '29.98',
  '10',
  '6',
  '3',
  '13',
  '6',
  '17',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 4, 0, 0),
  64,
  53,
  42,
  '45',
  '41',
  '39',
  '89',
  '68',
  '46',
  '30.11',
  '29.95',
  '29.87',
  '10',
  '6',
  '2',
  '10',
  '2',
  '18',
  '0.15',
  'Rain'),
 (datetime.datetime(2014, 2, 5, 0, 0),
  48,
  40,
  31,
  '42',
  '26',
  '16',
  '80',
  '60',
  '39',
  '30.5',
  '30.37',
  '30.13',
  '10',
  '10',
  '10',
  '16',
  '10',
  '24',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 6, 0, 0),
  32,
  29,
  26,
  '17',
  '15',
  '13',
  '58',
  '54',
  '49',
  '30.57',
  '30.48',
  '30.42',
  '10',
  '10',
  '10',
  '15',
  '8',
  '23',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 7, 0, 0),
  38,
  34,
  29,
  '29',
  '24',
  '17',
  '78',
  '68',
  '58',
  '30.41',
  '30.32',
  '30.24',
  '10',
  '7',
  '2',
  '8',
  '3',
  '12',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 8, 0, 0),
  65,
  51,
  37,
  '42',
  '36',
  '29',
  '85',
  '63',
  '40',
  '30.26',
  '30.17',
  '30.03',
  '10',
  '7',
  '3',
  '14',
  '5',
  '21',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 9, 0, 0),
  76,
  59,
  41,
  '53',
  '45',
  '38',
  '96',
  '70',
  '44',
  '30.12',
  '30.05',
  '29.93',
  '10',
  '5',
  '0',
  '13',
  '4',
  '20',
  '0',
  'Fog'),
 (datetime.datetime(2014, 2, 10, 0, 0),
  60,
  48,
  35,
  '49',
  '36',
  '30',
  '82',
  '74',
  '66',
  '30.23',
  '30.15',
  '30.02',
  '10',
  '8',
  '4',
  '15',
  '9',
  '23',
  'T',
  'Rain'),
 (datetime.datetime(2014, 2, 11, 0, 0),
  36,
  35,
  33,
  '31',
  '29',
  '27',
  '89',
  '80',
  '70',
  '30.3',
  '30.24',
  '30.19',
  '9',
  '5',
  '1',
  '15',
  '9',
  '23',
  '0.1',
  'Rain'),
 (datetime.datetime(2014, 2, 12, 0, 0),
  57,
  45,
  33,
  '34',
  '29',
  '27',
  '75',
  '57',
  '38',
  '30.27',
  '30.18',
  '30.08',
  '10',
  '9',
  '7',
  '14',
  '5',
  '22',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 13, 0, 0),
  69,
  51,
  32,
  '38',
  '34',
  '28',
  '85',
  '58',
  '30',
  '30.11',
  '30.02',
  '29.93',
  '10',
  '10',
  '10',
  '10',
  '4',
  '19',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 14, 0, 0),
  86,
  67,
  47,
  '48',
  '37',
  '22',
  '86',
  '51',
  '15',
  '30.08',
  '29.93',
  '29.85',
  '10',
  '10',
  '8',
  '18',
  '6',
  '30',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 15, 0, 0),
  76,
  59,
  42,
  '52',
  '35',
  '22',
  '64',
  '43',
  '22',
  '30.17',
  '30.09',
  '30.01',
  '10',
  '10',
  '10',
  '15',
  '5',
  '23',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 16, 0, 0),
  76,
  68,
  59,
  '61',
  '57',
  '53',
  '90',
  '74',
  '57',
  '30.08',
  '30.01',
  '29.94',
  '10',
  '5',
  '0',
  '13',
  '5',
  '23',
  '0',
  'Fog'),
 (datetime.datetime(2014, 2, 17, 0, 0),
  81,
  70,
  58,
  '62',
  '50',
  '29',
  '87',
  '52',
  '17',
  '30.12',
  '30.03',
  '29.92',
  '10',
  '8',
  '2',
  '15',
  '5',
  '23',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 18, 0, 0),
  82,
  69,
  55,
  '63',
  '53',
  '32',
  '78',
  '55',
  '32',
  '30.1',
  '30',
  '29.89',
  '10',
  '10',
  '9',
  '13',
  '4',
  '20',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 19, 0, 0),
  82,
  73,
  63,
  '62',
  '60',
  '59',
  '93',
  '70',
  '47',
  '29.93',
  '29.85',
  '29.72',
  '10',
  '9',
  '2',
  '15',
  '7',
  '25',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 20, 0, 0),
  83,
  70,
  57,
  '64',
  '50',
  '27',
  '81',
  '48',
  '15',
  '30.09',
  '29.85',
  '29.71',
  '10',
  '9',
  '7',
  '16',
  '8',
  '28',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 21, 0, 0),
  72,
  57,
  41,
  '33',
  '27',
  '22',
  '67',
  '43',
  '19',
  '30.21',
  '30.11',
  '30.03',
  '10',
  '10',
  '10',
  '14',
  '5',
  '20',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 22, 0, 0),
  77,
  63,
  48,
  '57',
  '46',
  '30',
  '73',
  '53',
  '32',
  '30.05',
  '29.96',
  '29.87',
  '10',
  '10',
  '10',
  '14',
  '6',
  '22',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 23, 0, 0),
  86,
  74,
  62,
  '61',
  '56',
  '44',
  '84',
  '57',
  '29',
  '30.05',
  '29.95',
  '29.88',
  '10',
  '10',
  '7',
  '15',
  '4',
  '24',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 24, 0, 0),
  76,
  66,
  55,
  '63',
  '51',
  '43',
  '81',
  '65',
  '49',
  '30.1',
  '30.04',
  '29.99',
  '10',
  '9',
  '5',
  '12',
  '4',
  '18',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 25, 0, 0),
  71,
  62,
  52,
  '65',
  '60',
  '47',
  '93',
  '85',
  '77',
  '30.06',
  '30.01',
  '29.95',
  '10',
  '4',
  '1',
  '12',
  '5',
  '20',
  'T',
  'Rain'),
 (datetime.datetime(2014, 2, 26, 0, 0),
  52,
  44,
  36,
  '46',
  '33',
  '21',
  '83',
  '63',
  '43',
  '30.26',
  '30.18',
  '30.06',
  '10',
  '8',
  '2',
  '20',
  '8',
  '29',
  '0.11',
  'Rain'),
 (datetime.datetime(2014, 2, 27, 0, 0),
  59,
  45,
  31,
  '32',
  '27',
  '21',
  '82',
  '56',
  '29',
  '30.22',
  '30.1',
  '29.94',
  '10',
  '10',
  '10',
  '12',
  '3',
  '17',
  '0',
  ' '),
 (datetime.datetime(2014, 2, 28, 0, 0),
  80,
  62,
  44,
  '50',
  '46',
  '35',
  '83',
  '60',
  '37',
  '29.92',
  '29.85',
  '29.75',
  '10',
  '10',
  '7',
  '13',
  '6',
  '21',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 1, 0, 0),
  82,
  68,
  53,
  '65',
  '57',
  '48',
  '93',
  '74',
  '54',
  '30.02',
  '29.95',
  '29.87',
  '10',
  '7',
  '0',
  '16',
  '5',
  '27',
  '0',
  'Fog'),
 (datetime.datetime(2014, 3, 2, 0, 0),
  73,
  51,
  28,
  '67',
  '45',
  '20',
  '89',
  '79',
  '69',
  '30.31',
  '30.05',
  '29.88',
  '10',
  '8',
  '2',
  '20',
  '10',
  '37',
  '0.08',
  'Rain'),
 (datetime.datetime(2014, 3, 3, 0, 0),
  47,
  36,
  24,
  '27',
  '20',
  '12',
  '75',
  '56',
  '37',
  '30.44',
  '30.33',
  '30.25',
  '10',
  '9',
  '4',
  '18',
  '10',
  '29',
  '0.08',
  'Rain , Thunderstorm'),
 (datetime.datetime(2014, 3, 4, 0, 0),
  50,
  40,
  30,
  '36',
  '31',
  '26',
  '92',
  '72',
  '52',
  '30.31',
  '30.18',
  '30.06',
  '10',
  '8',
  '2',
  '9',
  '4',
  '13',
  '0.17',
  'Rain'),
 (datetime.datetime(2014, 3, 5, 0, 0),
  53,
  46,
  38,
  '43',
  '39',
  '35',
  '86',
  '76',
  '66',
  '30.18',
  '30.06',
  '29.99',
  '10',
  '7',
  '4',
  '13',
  '3',
  '16',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 6, 0, 0),
  65,
  54,
  43,
  '42',
  '38',
  '35',
  '89',
  '62',
  '34',
  '30.28',
  '30.18',
  '30.08',
  '10',
  '8',
  '4',
  '13',
  '4',
  '20',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 7, 0, 0),
  67,
  53,
  39,
  '50',
  '42',
  '36',
  '86',
  '65',
  '44',
  '30.1',
  '29.99',
  '29.88',
  '10',
  '9',
  '5',
  '16',
  '6',
  '22',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 8, 0, 0),
  59,
  52,
  44,
  '57',
  '49',
  '39',
  '93',
  '88',
  '83',
  '30.3',
  '30.09',
  '29.9',
  '10',
  '3',
  '1',
  '14',
  '4',
  '21',
  '0.74',
  'Rain , Thunderstorm'),
 (datetime.datetime(2014, 3, 9, 0, 0),
  58,
  49,
  39,
  '45',
  '39',
  '31',
  '86',
  '71',
  '55',
  '30.37',
  '30.29',
  '30.22',
  '10',
  '9',
  '2',
  '15',
  '5',
  '23',
  '0.11',
  'Rain'),
 (datetime.datetime(2014, 3, 10, 0, 0),
  71,
  61,
  50,
  '56',
  '51',
  '45',
  '84',
  '69',
  '53',
  '30.25',
  '30.08',
  '29.94',
  '10',
  '9',
  '4',
  '12',
  '3',
  '17',
  '0.01',
  'Rain'),
 (datetime.datetime(2014, 3, 11, 0, 0),
  83,
  70,
  56,
  '56',
  '54',
  '52',
  '93',
  '66',
  '39',
  '29.93',
  '29.77',
  '29.58',
  '10',
  '9',
  '4',
  '14',
  '5',
  '22',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 12, 0, 0),
  70,
  60,
  49,
  '50',
  '28',
  '16',
  '56',
  '36',
  '16',
  '30.3',
  '30.13',
  '29.73',
  '10',
  '10',
  '10',
  '24',
  '11',
  '37',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 13, 0, 0),
  68,
  52,
  37,
  '40',
  '26',
  '20',
  '68',
  '35',
  '21',
  '30.37',
  '30.26',
  '30.12',
  '10',
  '10',
  '10',
  '9',
  '4',
  '18',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 14, 0, 0),
  75,
  62,
  49,
  '59',
  '51',
  '43',
  '86',
  '68',
  '49',
  '30.11',
  '30.04',
  '29.95',
  '10',
  '10',
  '10',
  '13',
  '5',
  '24',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 15, 0, 0),
  74,
  68,
  62,
  '64',
  '62',
  '59',
  '93',
  '81',
  '68',
  '29.97',
  '29.86',
  '29.68',
  '10',
  '5',
  '0',
  '12',
  '4',
  '17',
  '0.07',
  'Fog , Rain'),
 (datetime.datetime(2014, 3, 16, 0, 0),
  64,
  56,
  48,
  '58',
  '45',
  '32',
  '93',
  '66',
  '39',
  '30.07',
  '29.9',
  '29.7',
  '10',
  '10',
  '10',
  '24',
  '11',
  '36',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 17, 0, 0),
  68,
  55,
  41,
  '31',
  '26',
  '20',
  '53',
  '36',
  '18',
  '30.06',
  '29.94',
  '29.78',
  '10',
  '10',
  '10',
  '16',
  '6',
  '26',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 18, 0, 0),
  83,
  65,
  47,
  '56',
  '42',
  '31',
  '73',
  '49',
  '24',
  '29.83',
  '29.74',
  '29.67',
  '10',
  '10',
  '10',
  '18',
  '8',
  '26',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 19, 0, 0),
  72,
  62,
  51,
  '55',
  '37',
  '28',
  '80',
  '52',
  '24',
  '30.21',
  '30.07',
  '29.88',
  '10',
  '9',
  '6',
  '15',
  '6',
  '26',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 20, 0, 0),
  76,
  59,
  42,
  '40',
  '36',
  '31',
  '82',
  '52',
  '21',
  '30.25',
  '30.15',
  '30.04',
  '10',
  '10',
  '10',
  '10',
  '2',
  '15',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 21, 0, 0),
  80,
  67,
  54,
  '60',
  '54',
  '41',
  '93',
  '69',
  '45',
  '30.03',
  '29.95',
  '29.83',
  '10',
  '8',
  '0',
  '17',
  '7',
  '27',
  '0',
  'Fog'),
 (datetime.datetime(2014, 3, 22, 0, 0),
  77,
  69,
  61,
  '65',
  '62',
  '51',
  '100',
  '80',
  '60',
  '30.02',
  '29.95',
  '29.88',
  '10',
  '7',
  '1',
  '12',
  '4',
  '17',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 23, 0, 0),
  61,
  54,
  47,
  '51',
  '43',
  '36',
  '72',
  '62',
  '51',
  '30.27',
  '30.19',
  '30.05',
  '10',
  '10',
  '9',
  '17',
  '9',
  '30',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 24, 0, 0),
  66,
  58,
  50,
  '47',
  '42',
  '38',
  '72',
  '58',
  '44',
  '30.24',
  '30.14',
  '30.03',
  '10',
  '10',
  '10',
  '10',
  '3',
  '15',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 25, 0, 0),
  69,
  57,
  44,
  '46',
  '38',
  '31',
  '93',
  '61',
  '28',
  '30.35',
  '30.24',
  '30.14',
  '10',
  '10',
  '7',
  '15',
  '5',
  '22',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 26, 0, 0),
  66,
  60,
  54,
  '55',
  '47',
  '30',
  '78',
  '57',
  '36',
  '30.2',
  '30.08',
  '29.95',
  '10',
  '10',
  '6',
  '22',
  '10',
  '33',
  'T',
  'Rain'),
 (datetime.datetime(2014, 3, 27, 0, 0),
  82,
  72,
  61,
  '68',
  '63',
  '56',
  '100',
  '78',
  '55',
  '29.95',
  '29.83',
  '29.73',
  '10',
  '7',
  '1',
  '16',
  '8',
  '26',
  '0.01',
  'Rain'),
 (datetime.datetime(2014, 3, 28, 0, 0),
  89,
  76,
  63,
  '67',
  '61',
  '49',
  '90',
  '64',
  '37',
  '30',
  '29.79',
  '29.7',
  '10',
  '8',
  '2',
  '18',
  '5',
  '27',
  '0',
  'Thunderstorm'),
 (datetime.datetime(2014, 3, 29, 0, 0),
  77,
  64,
  51,
  '48',
  '40',
  '30',
  '68',
  '43',
  '18',
  '30.28',
  '30.18',
  '30.04',
  '10',
  '10',
  '10',
  '13',
  '5',
  '21',
  '0',
  ' '),
 (datetime.datetime(2014, 3, 30, 0, 0),
  79,
  62,
  45,

In [164]:
import pandas as pd
austin_weather_df = pd.DataFrame(results)
austin_weather_df

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,2013-12-21,74,60,45,67,49,43,93,75,57,...,29.68,29.59,10,7,2,20,4,31,0.46,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43,36,28,93,68,43,...,30.13,29.87,10,10,5,16,6,25,0,
2,2013-12-23,58,45,32,31,27,23,76,52,27,...,30.49,30.41,10,10,10,8,3,12,0,
3,2013-12-24,61,46,31,36,28,21,89,56,22,...,30.45,30.3,10,10,7,12,4,20,0,
4,2013-12-25,58,50,41,44,40,36,86,71,56,...,30.33,30.27,10,10,7,10,2,16,T,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,2017-07-27,103,89,75,71,67,61,82,54,25,...,29.97,29.88,10,10,10,12,5,21,0,
315,2017-07-28,105,91,76,71,64,55,87,54,20,...,29.9,29.81,10,10,10,14,5,20,0,
316,2017-07-29,107,92,77,72,64,55,82,51,19,...,29.86,29.79,10,10,10,12,4,17,0,
317,2017-07-30,106,93,79,70,68,63,69,48,27,...,29.91,29.87,10,10,10,13,4,20,0,
318,2017-07-31,99,88,77,66,61,54,64,43,22,...,29.97,29.91,10,10,10,12,4,20,0,

In [165]:
query = ("SELECT * FROM austin_weather;")
austin_weather_df = pd.read_sql_query(query, con=cnx)
austin_weather_df

/var/folders/64/f4b7nt8x7g7cqf657vzs8__w0000gn/T/ipykernel_42454/4193830086.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  austin_weather_df = pd.read_sql_query(query, con=cnx)

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,2013-12-21,74,60,45,67,49,43,93,75,57,...,29.68,29.59,10,7,2,20,4,31,0.46,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43,36,28,93,68,43,...,30.13,29.87,10,10,5,16,6,25,0,
2,2013-12-23,58,45,32,31,27,23,76,52,27,...,30.49,30.41,10,10,10,8,3,12,0,
3,2013-12-24,61,46,31,36,28,21,89,56,22,...,30.45,30.3,10,10,7,12,4,20,0,
4,2013-12-25,58,50,41,44,40,36,86,71,56,...,30.33,30.27,10,10,7,10,2,16,T,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,2017-07-27,103,89,75,71,67,61,82,54,25,...,29.97,29.88,10,10,10,12,5,21,0,
315,2017-07-28,105,91,76,71,64,55,87,54,20,...,29.9,29.81,10,10,10,14,5,20,0,
316,2017-07-29,107,92,77,72,64,55,82,51,19,...,29.86,29.79,10,10,10,12,4,17,0,
317,2017-07-30,106,93,79,70,68,63,69,48,27,...,29.91,29.87,10,10,10,13,4,20,0,
318,2017-07-31,99,88,77,66,61,54,64,43,22,...,29.97,29.91,10,10,10,12,4,20,0,


# Challenge 1 - Describe the Dataset

#### Describe the dataset you have loaded: 
- Look at the variables and their types
- Examine the descriptive statistics of the numeric variables 
- Look at the first five rows of all variables to evaluate the categorical variables as well

In [166]:
austin_weather_df.shape

(319, 21)

In [167]:
# Your code here
austin_weather_df.columns

Index(['Date', 'TempHighF', 'TempAvgF', 'TempLowF', 'DewPointHighF',
       'DewPointAvgF', 'DewPointLowF', 'HumidityHighPercent',
       'HumidityAvgPercent', 'HumidityLowPercent',
       'SeaLevelPressureHighInches', 'SeaLevelPressureAvgInches',
       'SeaLevelPressureLowInches', 'VisibilityHighMiles',
       'VisibilityAvgMiles', 'VisibilityLowMiles', 'WindHighMPH', 'WindAvgMPH',
       'WindGustMPH', 'PrecipitationSumInches', 'Events'],
      dtype='object')

In [152]:
# Your code here
austin_weather_df.dtypes

Date                          datetime64[ns]
TempHighF                              int64
TempAvgF                               int64
TempLowF                               int64
DewPointHighF                         object
DewPointAvgF                          object
DewPointLowF                          object
HumidityHighPercent                   object
HumidityAvgPercent                    object
HumidityLowPercent                    object
SeaLevelPressureHighInches            object
SeaLevelPressureAvgInches             object
SeaLevelPressureLowInches             object
VisibilityHighMiles                   object
VisibilityAvgMiles                    object
VisibilityLowMiles                    object
WindHighMPH                           object
WindAvgMPH                            object
WindGustMPH                           object
PrecipitationSumInches                object
Events                                object
dtype: object

In [125]:
# Your code here
austin_weather_df.head()

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,2013-12-21,74,60,45,67,49,43,93,75,57,...,29.68,29.59,10,7,2,20,4,31,0.46,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43,36,28,93,68,43,...,30.13,29.87,10,10,5,16,6,25,0,
2,2013-12-23,58,45,32,31,27,23,76,52,27,...,30.49,30.41,10,10,10,8,3,12,0,
3,2013-12-24,61,46,31,36,28,21,89,56,22,...,30.45,30.3,10,10,7,12,4,20,0,
4,2013-12-25,58,50,41,44,40,36,86,71,56,...,30.33,30.27,10,10,7,10,2,16,T,

#### Given the information you have learned from examining the dataset, write down three insights about the data in a markdown cell below

#### Your Insights:

1. There are 21 variables in the dataset. 3 of them are numeric and the rest contain some text.

2. The average temperature in Austin ranged between around 70 degrees F and around 93 degrees F. The highest temperature observed during this period was 107 degrees F and the lowest was 19 degrees F.

3. When we look at the head function, we see that a lot of variables contain numeric data even though these columns are of object type. This means we might have to do some data cleansing.

#### Let's examine the DewPointAvgF variable by using the `unique()` function to list all unique values in this dataframe.

Describe what you find in a markdown cell below the code. What did you notice? What do you think made Pandas to treat this column as *object* instead of *int64*?

In [99]:
# Your code here
austin_weather_df['DewPointAvgF'].unique()

array(['49', '36', '27', '28', '40', '39', '41', '26', '42', '22', '48',
       '32', '8', '11', '45', '55', '61', '37', '47', '25', '23', '20',
       '33', '30', '29', '17', '14', '13', '54', '59', '15', '24', '34',
       '35', '57', '50', '53', '60', '46', '56', '51', '31', '38', '62',
       '43', '63', '64', '67', '66', '58', '70', '68', '65', '69', '71',
       '72', '-', '73', '74'], dtype=object)

In [30]:
# Your observation here
#because they are considered as string

The following is a list of columns misrepresented as `object`. Use this list to convert the columns to numeric using the `pandas.to_numeric` function in the next cell. If you encounter errors in converting strings to numeric values, you need to catch those errors and force the conversion by supplying `errors='coerce'` as an argument for `pandas.to_numeric`. Coercing will replace non-convertable elements with `NaN` which represents an undefined numeric value. This makes it possible for us to conveniently handle missing values in subsequent data processing.

*Hint: you may use a loop to change one column at a time but it is more efficient to use `apply`.*

In [153]:
wrong_type_columns = ['DewPointHighF', 'DewPointAvgF', 'DewPointLowF', 'HumidityHighPercent', 
                      'HumidityAvgPercent', 'HumidityLowPercent', 'SeaLevelPressureHighInches', 
                      'SeaLevelPressureAvgInches' ,'SeaLevelPressureLowInches', 'VisibilityHighMiles',
                      'VisibilityAvgMiles', 'VisibilityLowMiles', 'WindHighMPH', 'WindAvgMPH', 
                      'WindGustMPH', 'PrecipitationSumInches']

In [154]:
austin_weather_df[wrong_type_columns] = austin_weather_df[wrong_type_columns].apply(pd.to_numeric, errors='ignore')
austin_weather_df.head()

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,2013-12-21,74,60,45,67,49,43,93,75,57,...,29.68,29.59,10,7,2,20,4,31,0.46,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43,36,28,93,68,43,...,30.13,29.87,10,10,5,16,6,25,0,
2,2013-12-23,58,45,32,31,27,23,76,52,27,...,30.49,30.41,10,10,10,8,3,12,0,
3,2013-12-24,61,46,31,36,28,21,89,56,22,...,30.45,30.30,10,10,7,12,4,20,0,
4,2013-12-25,58,50,41,44,40,36,86,71,56,...,30.33,30.27,10,10,7,10,2,16,T,

In [220]:
austin_weather_df['Date'].dtypes

dtype('<M8[ns]')

In [197]:
austin_weather_df["DewPointHighF"]=pd.to_numeric(austin_weather_df["DewPointHighF"], errors = 'coerce')
austin_weather_df["DewPointAvgF"]=pd.to_numeric(austin_weather_df["DewPointAvgF"], errors = 'coerce')
austin_weather_df["DewPointLowF"]=pd.to_numeric(austin_weather_df["DewPointLowF"], errors = 'coerce')
austin_weather_df["HumidityHighPercent"]=pd.to_numeric(austin_weather_df["HumidityHighPercent"], errors = 'coerce')
austin_weather_df["HumidityAvgPercent"]=pd.to_numeric(austin_weather_df["HumidityAvgPercent"], errors = 'coerce')
austin_weather_df["HumidityLowPercent"]=pd.to_numeric(austin_weather_df["HumidityLowPercent"], errors = 'coerce')
austin_weather_df["SeaLevelPressureHighInches"]=pd.to_numeric(austin_weather_df["SeaLevelPressureHighInches"], errors = 'coerce')
austin_weather_df["SeaLevelPressureLowInches"]=pd.to_numeric(austin_weather_df["SeaLevelPressureLowInches"], errors = 'coerce')
austin_weather_df["VisibilityHighMiles"]=pd.to_numeric(austin_weather_df["VisibilityHighMiles"], errors = 'coerce')
austin_weather_df["VisibilityAvgMiles"]=pd.to_numeric(austin_weather_df["VisibilityAvgMiles"], errors = 'coerce')
austin_weather_df["VisibilityLowMiles"]=pd.to_numeric(austin_weather_df["VisibilityLowMiles"], errors = 'coerce')
austin_weather_df["WindHighMPH"]=pd.to_numeric(austin_weather_df["WindHighMPH"], errors = 'coerce')
austin_weather_df["WindAvgMPH"]=pd.to_numeric(austin_weather_df["WindAvgMPH"], errors = 'coerce')
austin_weather_df["WindGustMPH"]=pd.to_numeric(austin_weather_df["WindGustMPH"], errors = 'coerce')
austin_weather_df["PrecipitationSumInches"]=pd.to_numeric(austin_weather_df["PrecipitationSumInches"], errors = 'coerce')

In [198]:
austin_weather_df.dtypes

Date                          datetime64[ns]
TempHighF                              int64
TempAvgF                               int64
TempLowF                               int64
DewPointHighF                        float64
DewPointAvgF                         float64
DewPointLowF                         float64
HumidityHighPercent                  float64
HumidityAvgPercent                   float64
HumidityLowPercent                   float64
SeaLevelPressureHighInches           float64
SeaLevelPressureAvgInches            float64
SeaLevelPressureLowInches            float64
VisibilityHighMiles                  float64
VisibilityAvgMiles                   float64
VisibilityLowMiles                   float64
WindHighMPH                            int64
WindAvgMPH                             int64
WindGustMPH                            int64
PrecipitationSumInches               float64
Events                                object
dtype: object

In [221]:
austin_weather_df['Date'].dtypes

dtype('<M8[ns]')

#### Check if your code has worked by printing the data types again. You should see only two `object` columns (`Date` and `Events`) now. All other columns should be `int64` or `float64`.

In [199]:
# Your code here
object_columns = austin_weather_df.select_dtypes(include='object')
object_columns

                  Events
0    Rain , Thunderstorm
1
2
3
4
..                   ...
314
315
316
317
318

[319 rows x 1 columns]

In [200]:
object_columns

                  Events
0    Rain , Thunderstorm
1
2
3
4
..                   ...
314
315
316
317
318

[319 rows x 1 columns]

In [201]:
numerical_columns = austin_weather_df.select_dtypes(include='number')
numerical_columns

,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches
0,74,60,45,67.0,49.0,43.0,93.0,75.0,57.0,29.86,29.68,29.59,10.0,7.0,2.0,20,4,31,0.46
1,56,48,39,43.0,36.0,28.0,93.0,68.0,43.0,30.41,30.13,29.87,10.0,10.0,5.0,16,6,25,0.00
2,58,45,32,31.0,27.0,23.0,76.0,52.0,27.0,30.56,30.49,30.41,10.0,10.0,10.0,8,3,12,0.00
3,61,46,31,36.0,28.0,21.0,89.0,56.0,22.0,30.56,30.45,30.30,10.0,10.0,7.0,12,4,20,0.00
4,58,50,41,44.0,40.0,36.0,86.0,71.0,56.0,30.41,30.33,30.27,10.0,10.0,7.0,10,2,16,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,103,89,75,71.0,67.0,61.0,82.0,54.0,25.0,30.04,29.97,29.88,10.0,10.0,10.0,12,5,21,0.00
315,105,91,76,71.0,64.0,55.0,87.0,54.0,20.0,29.97,29.90,29.81,10.0,10.0,10.0,14,5,20,0.00
316,107,92,77,72.0,64.0,55.0,82.0,51.0,19.0,29.91,29.86,29.79,10.0,10.0,10.0,12,4,17,0.00
317,106,93,79,70.0,68.0,63.0,69.0,48.0,27.0,29.96,29.91,29.87,10.0,10.0,10.0,13,4,20,0.00
318,99,88,77,66.0,61.0,54.0,64.0,43.0,22.0,30.04,29.97,29.91,10.0,10.0,10.0,12,4,20,0.00

In [202]:
austin_weather_df['DewPointHighF'].dtypes

dtype('float64')

# Challenge 2 - Handle the Missing Data

#### Now that we have fixed the type mismatch, let's address the missing data.

By coercing the columns to numeric, we have created `NaN` for each cell containing characters. We should choose a strategy to address these missing data.

The first step is to examine how many rows contain missing data.

We check how much missing data we have by applying the `.isnull()` function to our dataset. To find the rows with missing data in any of its cells, we apply `.any(axis=1)` to the function. `austin.isnull().any(axis=1)` will return a column containing true if the row contains at least one missing value and false otherwise. Therefore we must subset our dataframe with this column. This will give us all rows with at least one missing value. 

#### In the next cell, identify all rows containing at least one missing value. Assign the dataframes with missing values to a variable called `missing_values`.

In [204]:
# Your code here
missing_values = austin_weather_df.isnull().any(axis=1)
missing_values

0      False
1      False
2      False
3      False
4       True
       ...
314    False
315    False
316    False
317    False
318    False
Length: 319, dtype: bool

There are multiple strategies to handle missing data. Below lists the most common ones data scientists use:

* Removing all rows or all columns containing missing data. This is the simplest strategy. It may work in some cases but not others.

* Filling all missing values with a placeholder value. 
    * For categorical data, `0`, `-1`, and `9999` are some commonly used placeholder values. 
    * For continuous data, some may opt to fill all missing data with the mean. This strategy is not optimal since it can increase the fit of the model.

* Filling the values using some algorithm. 

#### In our case, we will use a hybrid approach which is to first remove the data that contain most missing values then fill in the rest of the missing values with the *linear interpolation* algorithm.

#### Next, count the number of rows of `austin` and `missing_values`.

In [206]:
import pandas as pd

# Assuming 'df' is your DataFrame

# Step 1: Remove rows with most missing values
threshold = 0.5  # Set your threshold for considering a row for removal
austin_weather_df_cleaned = austin_weather_df.dropna(thresh=len(austin_weather_df.columns) * threshold)

# Step 2: Fill in remaining missing values with linear interpolation
austin_weather_df_cleaned_interpolated = austin_weather_df_cleaned.interpolate(method='linear')

# Display the cleaned and interpolated DataFrame
print(austin_weather_df_cleaned_interpolated)

          Date  TempHighF  TempAvgF  TempLowF  DewPointHighF  DewPointAvgF  \
0   2013-12-21         74        60        45           67.0          49.0
1   2013-12-22         56        48        39           43.0          36.0
2   2013-12-23         58        45        32           31.0          27.0
3   2013-12-24         61        46        31           36.0          28.0
4   2013-12-25         58        50        41           44.0          40.0
..         ...        ...       ...       ...            ...           ...
314 2017-07-27        103        89        75           71.0          67.0
315 2017-07-28        105        91        76           71.0          64.0
316 2017-07-29        107        92        77           72.0          64.0
317 2017-07-30        106        93        79           70.0          68.0
318 2017-07-31         99        88        77           66.0          61.0

     DewPointLowF  HumidityHighPercent  HumidityAvgPercent  \
0            43.0                 93.0                75.0
1            28.0                 93.0                68.0
2            23.0                 76.0                52.0
3            21.0                 89.0                56.0
4            36.0                 86.0                71.0
..            ...                  ...                 ...
314          61.0                 82.0                54.0
315          55.0                 87.0                54.0
316          55.0                 82.0                51.0
317          63.0                 69.0                48.0
318          54.0                 64.0                43.0

     HumidityLowPercent  ...  SeaLevelPressureAvgInches  \
0                  57.0  ...                      29.68
1                  43.0  ...                      30.13
2                  27.0  ...                      30.49
3                  22.0  ...                      30.45
4                  56.0  ...                      30.33
..                  ...  ...                        ...
314                25.0  ...                      29.97
315                20.0  ...                      29.90
316                19.0  ...                      29.86
317                27.0  ...                      29.91
318                22.0  ...                      29.97

     SeaLevelPressureLowInches  VisibilityHighMiles  VisibilityAvgMiles  \
0                        29.59                 10.0                 7.0
1                        29.87                 10.0                10.0
2                        30.41                 10.0                10.0
3                        30.30                 10.0                10.0
4                        30.27                 10.0                10.0
..                         ...                  ...                 ...
314                      29.88                 10.0                10.0
315                      29.81                 10.0                10.0
316                      29.79                 10.0                10.0
317                      29.87                 10.0                10.0
318                      29.91                 10.0                10.0

     VisibilityLowMiles  WindHighMPH  WindAvgMPH  WindGustMPH  \
0                   2.0           20           4           31
1                   5.0           16           6           25
2                  10.0            8           3           12
3                   7.0           12           4           20
4                   7.0           10           2           16
..                  ...          ...         ...          ...
314                10.0           12           5           21
315                10.0           14           5           20
316                10.0           12           4           17
317                10.0           13           4           20
318                10.0           12           4           20

     PrecipitationSumInches               Events
0                      0.46  Rain , Thunderstorm
1                      0.00
2                      0.00
3                      0.00
4                      0.00
..                      ...                  ...
314                    0.00
315                    0.00
316                    0.00
317                    0.00
318                    0.00

[319 rows x 21 columns]

#### Calculate the ratio of missing rows to total rows

In [208]:


# Calculate the ratio of missing rows to total rows
missing_ratio = austin_weather_df.isnull().any(axis=1).sum() / len(austin_weather_df)

print(f"Ratio of missing rows to total rows: {missing_ratio:.2%}")

Ratio of missing rows to total rows: 10.66%

As you can see, there is a large proportion of missing data (over 10%). Perhaps we should evaluate which columns have the most missing data and remove those columns. For the remaining columns, we will perform a linear approximation of the missing data.

We can find the number of missing rows in each column using the `.isna()` function. We then chain the `.sum` function to the `.isna()` function and find the number of missing rows per column

In [209]:

# Find the number of missing rows per column
missing_rows_per_column = austin_weather_df.isna().sum()

print("Number of missing rows per column:")
print(missing_rows_per_column)

Number of missing rows per column:
Date                           0
TempHighF                      0
TempAvgF                       0
TempLowF                       0
DewPointHighF                  4
DewPointAvgF                   4
DewPointLowF                   4
HumidityHighPercent            1
HumidityAvgPercent             1
HumidityLowPercent             1
SeaLevelPressureHighInches     0
SeaLevelPressureAvgInches      0
SeaLevelPressureLowInches      0
VisibilityHighMiles            4
VisibilityAvgMiles             4
VisibilityLowMiles             4
WindHighMPH                    0
WindAvgMPH                     0
WindGustMPH                    0
PrecipitationSumInches        31
Events                         0
dtype: int64

#### As you can see from the output, the majority of missing data is in one column called `PrecipitationSumInches`. What's the number of missing values in this column in ratio to its total number of rows?

In [211]:
# Your code here
austin_weather_df.drop(['PrecipitationSumInches'], inplace = True, axis=1)

Almost 10% data missing! Therefore, we prefer to remove this column instead of filling its missing values. 

#### Remove this column from `austin` using the `.drop()` function. Use the `inplace=True` argument.

*Hints:*

* By supplying `inplace=True` to `drop()`, the original dataframe object will be changed in place and the function will return `None`. In contrast, if you don't supply `inplace=True`, which is equivalent to supplying `inplace=False` because `False` is the default value, the original dataframe object will be kept and the function returns a copy of the transformed dataframe object. In the latter case, you'll have to assign the returned object back to your variable.

* Also, since you are dropping a column instead of a row, you'll need to supply `axis=1` to `drop()`.

[Reference for `pandas.DataFrame.drop`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html)

In [212]:
# Your code here 


# Print `austin` to confirm the column is indeed removed

austin_weather_df

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,Events
0,2013-12-21,74,60,45,67.0,49.0,43.0,93.0,75.0,57.0,29.86,29.68,29.59,10.0,7.0,2.0,20,4,31,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43.0,36.0,28.0,93.0,68.0,43.0,30.41,30.13,29.87,10.0,10.0,5.0,16,6,25,
2,2013-12-23,58,45,32,31.0,27.0,23.0,76.0,52.0,27.0,30.56,30.49,30.41,10.0,10.0,10.0,8,3,12,
3,2013-12-24,61,46,31,36.0,28.0,21.0,89.0,56.0,22.0,30.56,30.45,30.30,10.0,10.0,7.0,12,4,20,
4,2013-12-25,58,50,41,44.0,40.0,36.0,86.0,71.0,56.0,30.41,30.33,30.27,10.0,10.0,7.0,10,2,16,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,2017-07-27,103,89,75,71.0,67.0,61.0,82.0,54.0,25.0,30.04,29.97,29.88,10.0,10.0,10.0,12,5,21,
315,2017-07-28,105,91,76,71.0,64.0,55.0,87.0,54.0,20.0,29.97,29.90,29.81,10.0,10.0,10.0,14,5,20,
316,2017-07-29,107,92,77,72.0,64.0,55.0,82.0,51.0,19.0,29.91,29.86,29.79,10.0,10.0,10.0,12,4,17,
317,2017-07-30,106,93,79,70.0,68.0,63.0,69.0,48.0,27.0,29.96,29.91,29.87,10.0,10.0,10.0,13,4,20,
318,2017-07-31,99,88,77,66.0,61.0,54.0,64.0,43.0,22.0,30.04,29.97,29.91,10.0,10.0,10.0,12,4,20,

#### Next we will perform linear interpolation of the missing data.

This means that we will use a linear algorithm to estimate the missing data. Linear interpolation assumes that there is a straight line between the points and the missing point will fall on that line. This is a good enough approximation for weather related data. Weather related data is typically a time series. Therefore, we do not want to drop rows from our data if possible. It is prefereable to estimate the missing values rather than remove the rows. However, if you have data from a single point in time, perhaps a better solution would be to remove the rows. 

If you would like to read more about linear interpolation, you can do so [here](https://en.wikipedia.org/wiki/Linear_interpolation).

In the following cell, use the `.interpolate()` function on the entire dataframe. This time pass the `inplace=False` argument to the function and assign the interpolated dataframe to a new variable called `austin_fixed` so that we can compare with `austin`.

In [215]:
# Your code here
austin_fixed = austin_weather_df.interpolate(inplace= False )
austin_fixed

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,SeaLevelPressureHighInches,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,Events
0,2013-12-21,74,60,45,67.0,49.0,43.0,93.0,75.0,57.0,29.86,29.68,29.59,10.0,7.0,2.0,20,4,31,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43.0,36.0,28.0,93.0,68.0,43.0,30.41,30.13,29.87,10.0,10.0,5.0,16,6,25,
2,2013-12-23,58,45,32,31.0,27.0,23.0,76.0,52.0,27.0,30.56,30.49,30.41,10.0,10.0,10.0,8,3,12,
3,2013-12-24,61,46,31,36.0,28.0,21.0,89.0,56.0,22.0,30.56,30.45,30.30,10.0,10.0,7.0,12,4,20,
4,2013-12-25,58,50,41,44.0,40.0,36.0,86.0,71.0,56.0,30.41,30.33,30.27,10.0,10.0,7.0,10,2,16,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,2017-07-27,103,89,75,71.0,67.0,61.0,82.0,54.0,25.0,30.04,29.97,29.88,10.0,10.0,10.0,12,5,21,
315,2017-07-28,105,91,76,71.0,64.0,55.0,87.0,54.0,20.0,29.97,29.90,29.81,10.0,10.0,10.0,14,5,20,
316,2017-07-29,107,92,77,72.0,64.0,55.0,82.0,51.0,19.0,29.91,29.86,29.79,10.0,10.0,10.0,12,4,17,
317,2017-07-30,106,93,79,70.0,68.0,63.0,69.0,48.0,27.0,29.96,29.91,29.87,10.0,10.0,10.0,13,4,20,
318,2017-07-31,99,88,77,66.0,61.0,54.0,64.0,43.0,22.0,30.04,29.97,29.91,10.0,10.0,10.0,12,4,20,

#### Check to make sure `austin_fixed` contains no missing data. Also check `austin` - it still contains missing data.

In [217]:
# Your code here
austin_fixed.isnull().sum()

Date                          0
TempHighF                     0
TempAvgF                      0
TempLowF                      0
DewPointHighF                 0
DewPointAvgF                  0
DewPointLowF                  0
HumidityHighPercent           0
HumidityAvgPercent            0
HumidityLowPercent            0
SeaLevelPressureHighInches    0
SeaLevelPressureAvgInches     0
SeaLevelPressureLowInches     0
VisibilityHighMiles           0
VisibilityAvgMiles            0
VisibilityLowMiles            0
WindHighMPH                   0
WindAvgMPH                    0
WindGustMPH                   0
Events                        0
dtype: int64

In [218]:
austin_weather_df.isnull().sum()

Date                          0
TempHighF                     0
TempAvgF                      0
TempLowF                      0
DewPointHighF                 4
DewPointAvgF                  4
DewPointLowF                  4
HumidityHighPercent           1
HumidityAvgPercent            1
HumidityLowPercent            1
SeaLevelPressureHighInches    0
SeaLevelPressureAvgInches     0
SeaLevelPressureLowInches     0
VisibilityHighMiles           4
VisibilityAvgMiles            4
VisibilityLowMiles            4
WindHighMPH                   0
WindAvgMPH                    0
WindGustMPH                   0
Events                        0
dtype: int64

# Challenge 3 - Processing the `Events` Column

#### Our dataframe contains one true text column - the Events column. We should evaluate this column to determine how to process it.

Use the `value_counts()` function to evaluate the contents of this column

In [219]:
# Your code here:
austin_weather_df['Events'].value_counts()

Events
                             235
Rain                          35
Rain , Thunderstorm           28
Fog , Rain , Thunderstorm      7
Thunderstorm                   6
Fog                            5
Fog , Rain                     2
Rain , Snow                    1
Name: count, dtype: int64

Reading the values of `Events` and reflecting what those values mean in the context of data, you realize this column indicates what weather events had happened in a particular day.

#### What is the largest number of events happened in a single day? Enter your answer in the next cell.

In [ ]:
# Your answer:

#### We want to transform the string-type `Events` values to the numbers. This will allow us to apply machine learning algorithms easily.

How? We will create a new column for each type of events (i.e. *Rain*, *Snow*, *Fog*, *Thunderstorm*. In each column, we use `1` to indicate if the corresponding event happened in that day and use `0` otherwise.

Below we provide you a list of all event types. Loop the list and create a dummy column with `0` values for each event in `austin_fixed`. To create a new dummy column with `0` values, simply use `austin_fixed[event] = 0`.

In [ ]:
event_list = ['Snow', 'Fog', 'Rain', 'Thunderstorm']

# Your code here


# Print your new dataframe to check whether new columns have been created:

austin_fixed

#### Next, populate the actual values in the dummy columns of  `austin_fixed`.

You will check the *Events* column. If its string value contains `Rain`, then the *Rain* column should be `1`. The same for `Snow`, `Fog`, and `Thunderstorm`.

*Hints:*

* Use [`pandas.Series.str.contains()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.str.contains.html) to create the value series of each new column.

* What if the values you populated are booleans instead of numbers? You can cast the boolean values to numbers by using `.astype(int)`. For instance, `pd.Series([True, True, False]).astype(int)` will return a new series with values of `[1, 1, 0]`.

In [ ]:
# Your code here

#### Print out `austin_fixed` to check if the event columns are populated with the intended values

In [ ]:
# Your code here

#### If your code worked correctly, now we can drop the `Events` column as we don't need it any more.

In [ ]:
# Your code here

# Challenge 4 - Processing The `Date` Column

The `Date` column is another non-numeric field in our dataset. A value in that field looks like `'2014-01-06'` which consists of the year, month, and day connected with hyphens. One way to convert the date string to numerical is using a similar approach as we used for `Events`, namely splitting the column into numerical `Year`, `Month`, and `Day` columns. In this challenge we'll show you another way which is to use the Python `datetime` library's `toordinal()` function. Depending on what actual machine learning analysis you will conduct, each approach has its pros and cons. Our goal today is to practice data preparation so we'll skip the discussion here.

Here you can find the [reference](https://docs.python.org/3/library/datetime.html) and [example](https://stackoverflow.com/questions/39846918/convert-date-to-ordinal-python) for `toordinal`. The basic process is to first convert the string to a `datetime` object using `datetime.datetime.strptime`, then convert the `datetime` object to numerical using `toordinal`.

#### In the cell below, convert the `Date` column values from string to numeric values using `toordinal()`.

In [224]:
# Your code here
# Assuming 'austin_fixed' is your DataFrame and 'datetime_column' is the name of your datetime column
austin_fixed['numerical_date'] = austin_fixed['Date'].apply(lambda x: x.toordinal())

#### Print `austin_fixed` to check your `Date` column.

In [225]:
austin_fixed.head(5)

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,Events,numerical_date
0,2013-12-21,74,60,45,67.0,49.0,43.0,93.0,75.0,57.0,...,29.68,29.59,10.0,7.0,2.0,20,4,31,"Rain , Thunderstorm",735223
1,2013-12-22,56,48,39,43.0,36.0,28.0,93.0,68.0,43.0,...,30.13,29.87,10.0,10.0,5.0,16,6,25,,735224
2,2013-12-23,58,45,32,31.0,27.0,23.0,76.0,52.0,27.0,...,30.49,30.41,10.0,10.0,10.0,8,3,12,,735225
3,2013-12-24,61,46,31,36.0,28.0,21.0,89.0,56.0,22.0,...,30.45,30.30,10.0,10.0,7.0,12,4,20,,735226
4,2013-12-25,58,50,41,44.0,40.0,36.0,86.0,71.0,56.0,...,30.33,30.27,10.0,10.0,7.0,10,2,16,,735227

# Challenge 5 - Sampling and Holdout Sets

#### Now that we have processed the data for machine learning, we will separate the data to test and training sets.

We first train the model using only the training set. We check our metrics on the training set. We then apply the model to the test set and check our metrics on the test set as well. If the metrics are significantly more optimal on the training set, then we know we have overfit our model. We will need to revise our model to ensure it will be more applicable to data outside the test set.

#### In the next cells we will separate the data into a training set and a test set using the `train_test_split()` function in scikit-learn.

When using `scikit-learn` for machine learning, we first separate the data to predictor and response variables. This is the standard way of passing datasets into a model in `scikit-learn`. The `scikit-learn` will then find out whether the predictors and responses fit the model.

In the next cell, assign the `TempAvgF` column to `y` and the remaining columns to `X`. Your `X` should be a subset of `austin_fixed` containing the following columns: 

```['Date',
 'TempHighF',
 'TempLowF',
 'DewPointHighF',
 'DewPointAvgF',
 'DewPointLowF',
 'HumidityHighPercent',
 'HumidityAvgPercent',
 'HumidityLowPercent',
 'SeaLevelPressureHighInches',
 'SeaLevelPressureAvgInches',
 'SeaLevelPressureLowInches',
 'VisibilityHighMiles',
 'VisibilityAvgMiles',
 'VisibilityLowMiles',
 'WindHighMPH',
 'WindAvgMPH',
 'WindGustMPH',
 'Snow',
 'Fog',
 'Rain',
 'Thunderstorm']```
 
 Your `y` should be a subset of `austin_fixed` containing one column `TempAvgF`.

In [ ]:
# Your code here:

In the next cell, import `train_test_split` from `sklearn.model_selection`

In [ ]:
#Your code here:

Now that we have split the data to predictor and response variables and imported the `train_test_split()` function, split `X` and `y` into `X_train`, `X_test`, `y_train`, and `y_test`. 80% of the data should be in the training set and 20% in the test set. `train_test_split()` reference can be accessed [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html).


Enter your code in the cell below:

In [ ]:
#Your code here:

#### Congratulations! Now you have finished the preparation of the dataset!

# Bonus Challenge 1

#### While the above is the common practice to prepare most datasets, when it comes to time series data, we sometimes do not want to randomly select rows from our dataset.

This is because many time series algorithms rely on observations having equal time distances between them. In such cases, we typically select the majority of rows as the test data and the last few rows as the training data. We don't use `train_test_split()` to select the train/test data because it returns random selections.

In the following cell, compute the number of rows that account for 80% of our data and round it to the next integer. Assign this number to `ts_rows`.

In [ ]:
# Your code here:

Assign the first `ts_rows` rows of `X` to `X_ts_train` and the remaining rows to `X_ts_test`.

In [ ]:
# Your code here:

Assign the first `ts_rows` rows of `y` to `y_ts_train` and the remaining rows to `y_ts_test`.

In [ ]:
# Your code here: